export const BASE = "/";
export const PROFILE = "/profile";
export const LOGIN = "/login";
export const SIGNUP = "/signup";
export const VERIFY_EMAIL = "/verifyemail";
export const HOME = "/";
export const HABITS = "/habits-new"; // TODO: rename
export const TASKS = "/tasks";
export const PROJECTS = "/projects-new"; // TODO: rename
export const WIKI = "/wiki";
