name: unit tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Removing old modules
        run: rm -rf node_modules
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
